name: Auto Commit Every Day

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "Last update: $(date)" > last_update.txt

            - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated commit: $(date --utc)"
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: "${{ github.actor }}@users.noreply.github.com"
          GITHUB_TOKEN: ${{ secrets.PAT }}
